scallywag89/sets

- Gemfile.lock
- app/models/album.rb
- app/models/set_track.rb
- app/models/setlist.rb
- app/models/stack.rb
- app/models/stack_album.rb
- app/models/track.rb
- app/models/user.rb
> added validations and associations to models

- app/controllers/application_controller.rb
- db/migrate/20220707112848_add_columns_to_users.rb
- db/schema.rb
followed ActiveRecord instructions to add attributes to the auto generated devise user model
> added nickname, first_name and last_name to devise setup

- app/controllers/albums_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/set_tracks_controller.rb
- app/controllers/setlists_controller.rb
- app/controllers/stack_albums_controller.rb
- app/controllers/stacks_controller.rb
- app/controllers/tracks_controller.rb
> controllers

- Gemfile
- Gemfile.lock
- app/controllers/pages_controller.rb
- app/services/discogs_call.rb
Added the discogs gemfile and configured the .dotenv with the discogs keys
> added services directory and tested API call functionality

- app/controllers/application_controller.rb
can now access these pages without loggin in
> fixed devise to allow access to /home /search and /about

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/shared/_navbar.html.erb
1. added some custom colours to the bootstrap colours
2. added Poppins as the default font (can easily change later)
3. added hover effect to nav-links
4. added button class to log in button
Signed Out:
Signed In:
> coded navbar partial + styling

- Gemfile
- Gemfile.lock
- app/models/album.rb
- app/models/stack.rb
- db/seeds.rb
Generates 10 albums each with 8 tracks (they are not unique at this point)
Generates 5 users, which also creates their stacks
Populates each user stack with 4 albums
Generates 3 setlists for each user, each with 12 tracks in it
Creates an ADMIN profile for easy logins
Also added: 
" has_many :tracks, through: :albums"
to the Stack model, so we can call:
"User.stack.tracks"
Instead of:
"User.stack.albums.tracks"
> Added seed file, made tracks associate to Stack through albums

- app/assets/config/manifest.js
- app/assets/stylesheets/components/_hero.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/views/pages/home.html.erb
1. Added the videos folder to the asset pipeline in the js manifest
2. Imported the scss partial to the index
3. Altered the border radius to 4px in the bootstrap variables
4. Coded up the video - looking pretty cool!
> coded the video background

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
> footer with links to github

- Gemfile.lock
- app/assets/stylesheets/components/_avatar.scss
- app/views/shared/_navbar.html.erb
added avatar logic to navbar, default to logo if none attached
> added avatar logic to navbar

- Gemfile.lock
- app/javascript/controllers/index.js
- app/javascript/controllers/searchbar_controller.js
- app/views/shared/_searchbar.html.erb
> modified stimulus controller to style the switch on search bar

- app/models/album.rb
- db/migrate/20220719052119_add_cover_image_url_to_albums.rb
- db/schema.rb
- db/seeds.rb
> added cover image url to the album model

- app/views/shared/_navbar.html.erb
we want users to be able to search albums without needing to log in
> moved search and community links out of conditional

- app/controllers/pages_controller.rb
On pages controller, def set_setlist now has 'if current_user' before
> Added if statement to pages controller for setting setlist

- Gemfile.lock
- app/controllers/pages_controller.rb
- app/views/shared/_user_card.html.erb
Link Profile button to the other user's profile
> profilebutton

- app/controllers/users_controller.rb
- app/views/users/index.html.erb
Changed the followers sorted by Number of followers.
> sorted by number of followers

- app/views/shared/_navbar.html.erb
'Find music' to sign in page if user not logged in yet
> directToSignInPage

- app/controllers/users_controller.rb
easier code for Sort follower by numbers of followers.
> easier code

- app/assets/stylesheets/components/_from_stack.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_not_from_stack.scss
- app/assets/stylesheets/components/_setlist_show.scss
- app/controllers/setlists_controller.rb
- app/views/setlists/show.html.erb
- app/views/shared/_from_your_stack_card.html.erb
- app/views/shared/_not_in_stack_card.html.erb
Setlist show page now displays a card showing which albums you have in your set and which are missing
> From your set

- app/assets/stylesheets/components/_modal.scss
- app/views/shared/_search_modal.html.erb
Think this looks a little bit cleaner...
> some styling on search modal | add play button to preview track

- Gemfile.lock
- app/controllers/pages_controller.rb
fixed error for empty search req
> empty search fix

- app/controllers/pages_controller.rb
now you can also actually search for something!
> search empty fixed again lol

- app/controllers/set_tracks_controller.rb
- app/controllers/stack_albums_controller.rb
Change the redirect to 'request.referer' and stay in search page
> Stay search page

- app/controllers/set_tracks_controller.rb
- app/views/shared/_track_modal.html.erb
added if statement to display setlist dropdown, only if sets exist
> added if statement to track modal

- app/views/shared/_search_modal.html.erb
heroku throwing error due to too many requests to api
> deleted preview track feature

- app/views/shared/_navbar.html.erb
- app/views/shared/_track_modal.html.erb
1. changed the conditional to .nil? because setlists is a nilClass if they don't exist.
2. reverted to visitor being able to search if not logged in - otherwise the site is just a landing page lol
> search bug fixes

- app/views/setlists/show.html.erb
> positioned buttons at bottom of setlist | added 'Add to Set'

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_search.scss
- app/views/pages/search.html.erb
- app/views/shared/_track_modal.html.erb
just added some stuff to search page, changed the cursor on buttons, shifted some stuff, changed colour of add to set button so it matches add to stack button
> Search styling
